print("===Biodata===")
nama = input("Nama : ")
umur = int(input("Umur : "))
gender = (input("Jenis Kelamin :"))
tinggi = float(input("Tinggi :"))
no_hp = int(input("No Hp : "))
print(type(nama))
print(type(umur))
print(type(gender))
print(type(tinggi))
print(type(no_hp))
